### ISSUE TITLE
How to create CIDR from network and broadcast?

### ISSUE THREAD

**Issue by acim** [stbuehler/rust-cidr#10]
So, 218.188.0.0 and 218.191.255.255 should result into 10.0.0.0/24. I don't see any method in this crate to be able to achieve this. Thank you.

**Comment by acim** [comment]
Even worse, sometimes this may result in multiple CIDR's, for example 223.252.177.0 to 223.252.255.255 should result in:

```
223.252.177.0/24
223.252.178.0/23
223.252.180.0/22
223.252.184.0/21
223.252.192.0/18
```

**Comment by stbuehler** [comment]
Hi.

I think you mean "... should result in `218.188.0.0/14`."

You could try to find the smallest network that contains two given IPv4 addresses `a` and `b` (i.e. the longest shared prefix); to do that enable the `bitstring` feature, use [`let len = FixedBitString::shared_prefix_len(&a, &b, 32);`](https://docs.rs/bitstring/0.1.1/bitstring/fixed_bit_string/trait.FixedBitString.html#method.shared_prefix_len) to determine the length of the (longest) shared prefix - then construct a [`Ipv4Cidr`](https://docs.rs/cidr/latest/cidr/struct.Ipv4Cidr.html) from one of the addresses through [`Ipv4Inet`](https://docs.rs/cidr/latest/cidr/struct.Ipv4Inet.html): `IPv4Inet::new(a, len).network()`.

Or use [`https://docs.rs/bitstring/latest/bitstring/bit_string/trait.BitString.html#method.shared_prefix`](BitString::shared_prefix) to find the smallest network (again: longest shared prefix) that contains two `Ipv4Cidr`s (which could just be /32 host addresses).

Running this on network and broadcast address of a network can only return the network itself.

I'm not a big fan of the network address, broadcast address, netmasks and hostmasks, and not quite sure I want to add a special API for that.

Regarding your second challenge "Find the smallest set of networks covering an address range" I've written something in C# some time ago (https://stackoverflow.com/questions/13508231/how-can-i-convert-ip-range-to-cidr-in-c/16263105#16263105) - again not sure whether this should be added in this crate. I'll think about it.

**Comment by acim** [comment]
Yes, wrong copy&paste :) I created my own function already. Thank you.
