### ISSUE TITLE
const constructor

### ISSUE THREAD

**Issue by bryanlarsen** [stbuehler/rust-cidr#12]
It would really be nice if there was a const constructor for Ipv4Cidr and Ipv6Cidr.     This would simplify many of my tests.

**Comment by stbuehler** [comment]
`const` seems a worthy goal in all APIs.

Sadly this will need a little bit of `unsafe`; I can't find a "performant" way to convert `u128` to `Ipv6Addr` (`Ipv6Addr::from` can't be used in `const`) - see assembly output in [playground](https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=185950db58c69cc83dba372214cf082c).

**Comment by stbuehler** [comment]
This should be fixed in fb2682080605a68003af6d6e4673ec2ee1c89dad

**Comment by stbuehler** [comment]
Now released in [0.2.2](https://github.com/stbuehler/rust-cidr/releases/tag/cidr-0.2.2).
