### ISSUE TITLE
Wishlist:  from IpCidr to IpInet

### ISSUE THREAD

**Issue by bryanlarsen** [stbuehler/rust-cidr#13]
It would be convenient for me if `IpInet` had the `From<IpCidr>`, `From<Ipv6Cidr>` and `From<Ipv4Cidr>` traits implemented.

Not a big deal, I've got a few utility functions to do the conversion, but it's one of the things that feels like it should be in the library.   Also something I'm perfectly capable of created an MR for, so that's appropriate pushback...

**Comment by bryanlarsen** [comment]
This is in a routing context.   In that context, usually a Cidr is more appropriate than an Inet and so much of the API uses Cidr.   However, there are places where an Cidr doesn't work: a route destination which is essentially a network + a gateway within that network combined, for example.   And then there are places where we mix the two.   For example, with wireguard allowed-ips.   That ends up being a mixture of source and destination routes; wireguard only uses them as a Cidr, so we could convert the Inets -> Cidr before giving them to wireguard, but that's a lossy conversion so I prefer to convert the Cidr's to Inet's before giving them to wireguard.

**Comment by bryanlarsen** [comment]
allowed-ips in the wireguard examples are almost never valid CIDR's.     They always use the device address along with a network length.

**Comment by stbuehler** [comment]
I see your point in modifying existing configs.

But I didn't see any argument why `From` would be needed (i.e. why `.first()` isn't good enough), so closing this for now
