### ISSUE TITLE
Can't use from_string

### ISSUE THREAD

**Issue by robbieh** [stbuehler/rust-cidr#4]
I give up. I can't get this to work. Just trying to use from_string with AnyIpCidr. Can you tell me what I'm missing?
```

error[E0599]: no variant named `from_string` found for type `cidr::AnyIpCidr` in the current scope
  --> src/main.rs:45:30
   |
45 |     let c = cidr::AnyIpCidr::from_string(ipstr);
   |             -----------------^^^^^^^^^^^
   |             |
   |             variant not found in `cidr::AnyIpCidr`


```

**Comment by stbuehler** [comment]
You are probably looking for [`FromStr::from_str`](https://doc.rust-lang.org/nightly/core/str/trait.FromStr.html#tymethod.from_str); `FromStr` is not imported by default, and you'd usually use it through [`str::parse`](https://doc.rust-lang.org/nightly/std/primitive.str.html#method.parse) instead:

```rust
let c: cidr::AnyIpCidr = ipstr.parse().unwrap();
```
