### ISSUE TITLE
Add some benchmarks

### ISSUE THREAD

**Issue by Dennis-Zhang-SH** [stbuehler/rust-cidr#9]
Hi,
Thank you for the works, but I wonder if you could add some benchmarks for this crate?

**Comment by stbuehler** [comment]
I think the implementation should be good in "algorithm complexity" - as in I don't think there are better choices.
I.e. it should scale as well as it is possible.

But I'm not an expert at benchmarks, nor do I consider them worth my time, so I won't add them.
